#!/bin/bash
source ./.env
GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN \
WEBHOOK_ENDPOINT_PORT=$WEBHOOK_ENDPOINT_PORT \
WEBHOOK_ENDPOINT_SUFFIX=$WEBHOOK_ENDPOINT_SUFFIX \
WEBHOOK_SECRET=$WEBHOOK_SECRET \
WORK_DIR=$WORK_DIR \
$1 $2
