#!/bin/bash
source ./.env

GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN \
GITHUB_REPO=$GITHUB_REPO \
GITHUB_USER=$GITHUB_USER \
WEBHOOK_ENDPOINT_PORT=$WEBHOOK_ENDPOINT_PORT \
WEBHOOK_ENDPOINT_SUFFIX=$WEBHOOK_ENDPOINT_SUFFIX \
WEBHOOK_SECRET=$WEBHOOK_SECRET \
WORK_DIR=$WORK_DIR \
$1 src/app
